image: ubuntu

install:
- sudo apt-get update -qq
- sudo apt-get --no-install-recommends -y install cpanm libdist-zilla-perl

test_script:
- cd perl/modules/XML-Grammar-Fiction/
- dzil authordeps | xargs cpanm -n
- dzil listdeps | xargs cpanm -n
- dzil smoke
build: off
