image: ubuntu

install:
- sudo apt-get update -qq
- sudo apt-get --no-install-recommends -y install cpanminus libdist-zilla-perl libxml-libxslt-perl

test_script:
- cd perl/modules/XML-Grammar-Fiction/
- dzil authordeps | xargs sudo cpanm -n
- dzil listdeps | xargs sudo cpanm -n
- dzil smoke
build: off
