Code Block (<pre>/etc.) Element for XML-Grammar-Fiction/Screenplay
==================================================================
Shlomi Fish <shlomif@cpan.org>
:Date: 2020-11-04
:Revision: $Id$

[id="motivation"]
Motivation:
-----------

Used to encapsulate the ascii art at https://github.com/shlomif/shlomi-fish-homepage/blob/216ea2b871fa24d07d74ae68dda51b3b7b9e47b7/src/humour/by-others/hitchhiker-guide-to-star-trek-tng.txt
in an https://stackoverflow.com/questions/33929647/alt-attribute-for-ascii-art-in-html[accessible manner]
(and also better formatted for non-visual-impaired users).

[id="screenplay_text"]
Screenplay-Text:
----------------

[source,text,filename="perl/modules/XML-Grammar-Fiction/t/screenplay/data/proto-text/with-tags-inside-paragraphs.txt"]
----
<s id="top">

<s id="david_and_goliath">

[

<code_blk syntax="text" tag_role="asciiart" title="Star square" alt="The logo of the Square company">
&#124;******
&#124; *   *
&#124;  *  *
&#124; *   *
&#124;*    *
&#124;******
</code_blk>

David and <a href="http://en.wikipedia.org/wiki/Goliath">Goliath</a> are
standing by each other.



]

David: I will kill you.

Goliath: no way, you little idiot!

David: yes way!

++++: In the name of <a href="http://real-allah.tld/">Allah, the
<b>merciful</b>, real merciful</a>, I will show you the power of my sling.

++: I shall sling you and bing you till infinity.

[David takes his sling.]

Goliath: I'm still <a href="http://wait.tld/">waiting</a>.

David: so you are.

[David puts a stone in his sling and shoots Goliath. He hits.]

</s>

</s>
----

Notes:
~~~~~~

* For now `syntax` must be specified and have a `text` value.

* Similarly, `tag_role` must be specified and have an `asciiart` value.

* `title=` must be specified, but can be any utf8 text.

* `alt=` must be specified, but can be any utf8 text.

* There shall be an implicit removal of leading and trailing newlines
from the codeblock (matching the regex `(?:\r?\n)*`.
** There may be an attribute to override it in the future.

* Each line must start with a https://en.wikipedia.org/wiki/Vertical_bar or its
SGML entity which will be removed (to overcome the plaintext's processor's policy against
leading whitespace).

[id="screenplay_text_generated_html"]
Screenplay-Text rendered to HTML:
---------------------------------

[source,text,filename="perl/modules/XML-Grammar-Fiction/t/screenplay/data/proto-text/with-tags-inside-paragraphs--with-code_blk.xhtml"]
----
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:sp="http://web-cpan.berlios.de/modules/XML-Grammar-Screenplay/screenplay-xml-0.2/" xml:lang="">
  <head>
    <title>My Screenplay</title>
    <meta charset="utf-8"/>
  </head>
  <body>
    <main class="screenplay" id="index">
      <section class="scene" id="scene-top">
        <header>
          <h1 id="top">top</h1>
        </header>
        <section class="scene" id="scene-david_and_goliath">
          <header>
            <h2 id="david_and_goliath">david_and_goliath</h2>
          </header>
          <div class="description">
            <p>
            [
            </p>
            <figure class="asciiart">
<pre class="asciiart" title="Star square">
******
 *   *
  *  *
 *   *
*    *
******
</pre>
<figcaption>The logo of the Square company</figcaption>
           </figure>
        <p>
        David and <a href="http://en.wikipedia.org/wiki/Goliath">Goliath</a> are
standing by each other.
            ]
        </p>
          </div>
          <div class="saying">
            <p><strong class="sayer">David:</strong> I will kill you.
</p>
          </div>
          <div class="saying">
            <p><strong class="sayer">Goliath:</strong> no way, you little idiot!
</p>
          </div>
          <div class="saying">
            <p><strong class="sayer">David:</strong> yes way!
</p>
            <p><strong class="sayer">David:</strong> In the name of <a href="http://real-allah.tld/">Allah, the
<strong class="bold">merciful</strong>, real merciful</a>, I will show you the power of my sling.
</p>
            <p><strong class="sayer">David:</strong> I shall sling you and bing you till infinity.
</p>
          </div>
          <div class="description">
            <p>
            [
        David takes his sling.
            ]
        </p>
          </div>
          <div class="saying">
            <p><strong class="sayer">Goliath:</strong> I'm still <a href="http://wait.tld/">waiting</a>.
</p>
          </div>
          <div class="saying">
            <p><strong class="sayer">David:</strong> so you are.
</p>
          </div>
          <div class="description">
            <p>
            [
        David puts a stone in his sling and shoots Goliath. He hits.
            ]
        </p>
          </div>
        </section>
      </section>
    </main>
  </body>
</html>
----
